server:
  display-name: Wormhole for OpenAPI

# 数据源配置
#spring.datasource.name = mediator_wormhole
spring:
  datasource:
    url: jdbc:mysql://192.168.3.240:3306/mediator_wormhole?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: mytijian2015
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true
  dubbo:
    application:
      name: crm_dubbo
    registry:
      address: zookeeper://192.168.3.241:2181
    protocol:
      name: dubbo
    scan: com.mytijian.wormhole.web
  session:
    store-type: none

logging:
  file: logs/wormhole.log


## Mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.mytijian.wormhole.model
  global-config:
    id-type: 0
#mybatis-plus.global-config.field-strategy = 2
#mybatis-plus.global-config.auto-set-db-type = true
#mybatis-plus.global-config.db-column-underline = true
#mybatis-plus.global-config.refresh-mapper = true
#mybatis-plus.configuration.map-underscore-to-camel-case = true
#mybatis-plus.configuration.cache-enabled = false

info:
  build:
    artifact : com.mytijian.wormhole
    name: Wormhole
    description: OpenAPI for 3rd.
    version: 1.0.0
